# -*- coding: utf-8 -*-
"""Udemy_matriz.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fG6SOU3TEWqMOZLdFW-awgDkQnGdcUVX
"""

import sympy as sp
sp.init_printing()

Matriz_1 = sp.Matrix([[1,2],[4,5]])
#inversa
inv_1 = Matriz_1**(-1)
#Transposta
trans_1 = Matriz_1.T
#determinante
det_1 = Matriz_1.det()
print('matriz',Matriz_1)
print('inversa',inv_1)
print('transposta',trans_1)
print('determinante',det_1)

Matriz_2 = sp.Matrix([[sp.cos(sp.pi/4),-sp.sin(sp.pi/4)],[sp.sin(sp.pi/4),sp.cos(sp.pi/4)]])
#inversa
inv_2 = Matriz_2**(-1)
#Transposta
trans_2 = Matriz_2.T
#determinante
det_2 = Matriz_2.det()
print('matriz',Matriz_2)
print('inversa',inv_2)
print('transposta',trans_2)
print('determinante',det_2)

Matriz_3 = sp.Matrix([[2,-2],[-2,5]])
#inversa
inv_3 = Matriz_3**(-1)
#Transposta
trans_3 = Matriz_3.T
#determinante
det_3 = Matriz_3.det()
print('matriz',Matriz_3)
print('inversa',inv_3)
print('transposta',trans_3)
print('determinante',det_3)

Matriz_4 = sp.Matrix([[2,2],[4,4]])
#inversa
#inv_4 = Matriz_4**(-1) a matriz n inverte pois seu det é 0
#Transposta
trans_4 = Matriz_4.T
#determinante
det_4 = Matriz_4.det()
print('matriz',Matriz_4)
#print('inversa',inv_4)
print('transposta',trans_4)
print('determinante',det_4)